version: "3.1"

volumes:
  www:

networks:
  proxy:
    external:
      name: public_proxy

services:
  php:
    image: y/p06_php_web2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - www:/var/www/html
  httpd:
    image: itsziget/httpd24
    volumes:
      - www:/var/www/html
    environment:
      SRV_PHP: 1
      SRV_DOCROOT: /var/www/html
      VIRTUAL_HOST: web2.$XIP
    networks:
      - default
      - proxy